package com.orm;

/**
 * TYuangong generated by MyEclipse Persistence Tools
 */

public class Tlou implements java.io.Serializable
{

	private String id;
	private String louhao;
	private String del;
	
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getLouhao() {
		return louhao;
	}
	public void setLouhao(String louhao) {
		this.louhao = louhao;
	}
	public String getDel() {
		return del;
	}
	public void setDel(String del) {
		this.del = del;
	}
		
}